### PR TITLE
Adds Missing Tab Menu Item Info

### PR DESCRIPTION
**Pull request by HappyGoLucky1**
Should fix setting up the icons for Community and Plugin Center

### CODE REVIEW

**Comment by HappyGoLucky1** [comment]
Schemas would have to add 
Clockwork.option:SetKey("icon_data_plugin_center", {path = "blah/blah", size = nil});

But this sets up the stuff for it

**Comment by VortixDev** [comment]
Thanks for the request. Could you clarify the expected result of these changes? Currently, CloudAuthX adds the plugin center and community tabs through `MenuItemsAdd` already, so repeating the addition would only serve to duplicate the tab menu buttons. With respect to the changing of icons, the `icon_data_*` keys can be used already (even for the community and plugin centre buttons), as they are used by CAX.

Regarding the practical effect of the changes: 
 - The `communityName` and `pluginCenterName` aren't defined within the changes to `cl_kernel.lua`, so the first non-self parameter going into `menuItems.Add` is nil in each case
 - A `cwCommunity` panel is not defined (rather, `cwCloudSixteenForums` is used by CAX)
 - The `description_community` and `description_plugin_center` keys are used, but not defined

**Comment by HappyGoLucky1** [comment]
Ah, I didn't think about it being in CAX, if that is the case then this is redundant.

**Comment by VortixDev** [comment]
Thanks nonetheless.

**Pull request closed without merging**
