### PR TITLE
Added a hook that gets called after the character initialized and knockback hook

### PR DESCRIPTION
**Pull request by karl-police**
Added a hook that gets called after the character initialized

### CODE REVIEW

**Comment by kurozael** [comment]
Why would you call a hook called ‘OnPlayerCharacterInitialized’ inside a hook callback called ‘PlayerCharacterInitialized’? The hook already exists!

Also we don’t prefix hooks with ‘On’, and we call hooks with ‘cwPlugin:Call’ not with ‘hook.Call’ as that is just for regular GMod hooks.

**Comment by karl-police** [comment]
No, PlayerCharacterInitialized sadly doesn't work how I wanted it to work. I require OnPlayerCharacterInitialized, because I need all the information

which class got assigned, because after it got initialized it will check for the rank and assign it a class, which when I just use PlayerCharacterInitialized can be achieved.

**Comment by karl-police** [comment]
fixed the typo

**Comment by karl-police** [comment]
Added a new hook called PlayerCanTakeKnockbackFromDamage

**Pull request merged**
