### PR TITLE
Added 'return true' to CanCraft

### PR DESCRIPTION
**Pull request by TacticalToaster**
This avoids screwing with existing crafting recipes.

### CODE REVIEW

**Comment by xRJx** [comment]
Can you explain what the intended results of this is supposed to be? From what I'm seeing from this change, the default return will never be called on line 266 if the PR is merged since line 263 would always return true.

See here: 
https://github.com/CloudSixteen/Clockwork/blob/2bc92f40e990f75b45162e51ba8925a5907dc9db/Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_crafting.lua#L263

https://github.com/CloudSixteen/Clockwork/blob/2bc92f40e990f75b45162e51ba8925a5907dc9db/Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_crafting.lua#L266

**Comment by VortixDev** [comment]
@xRJx The problem is that what you describe seems to be the case in the current implementation. As `blueprint.CanCraft` is defined by default as an empty function, it passes the `if (blueprintTable.CanCraft) then` check. Since it is empty, it returns nothing. As a result, `Clockwork.crafting.CanCraft` receives and returns `nil` when it calls `blueprint.CanCraft`, and so all old blueprints which don't implement this function are no longer craftable as a side-effect.

To resolve this it seems either the default implementation of `blueprint.CanCraft` should be changed to return `true` by default, or the default definition should be removed to avoid problems for pre-existing blueprints.

**Comment by xRJx** [comment]
Hmm... I see what you mean. How about we change line 262 to this?
`if (blueprintTable.CanCraft == true or blueprintTable.CanCraft == false) then`

This way it'll only return on line 263 if a boolean is returned from calling blueprintTable.CanCraft on line 262. I believe this should address both of our concerns.

Alternatively we could do this on line 262:
`if (type(blueprintTable.CanCraft) == "boolean")`

Thoughts?

**Comment by VortixDev** [comment]
Sounds good. Of course, in implementation I'd make sure to localise the call of `blueprintTable.CanCraft` so that it doesn't have to be called again for the return. Also, we could use `isbool` to condense the statement. Alternatively, we could merge the if statements with the return to get the following:
```return blueprintTable.CanCraft and blueprintTable:CanCraft(player) != false or !blueprintTable.CanCraft```

**Pull request merged**
