### PR TITLE
Fix wrong language format.

### PR DESCRIPTION
**Pull request by 10sa**
Update Korean translation.

### CODE REVIEW

**Comment by murray-elijah** [comment]
I guess this may as well be added? I don't speak Korean so I can't verify but I'm presuming the translation is correct.

**Comment by 10sa** [comment]
@murray-elijah It just format fix for string.format function. Not translation.

**Comment by murray-elijah** [comment]
Well that's what I get for looking at it at 4am, lmao.

**Comment by xRJx** [comment]
These changes look good to me. I'll merge them now.

**Pull request merged**
