### PR TITLE
Add more possibilties for plugin creators when using thirdperson

### PR DESCRIPTION
**Pull request by karl-police**

### CODE REVIEW

**Comment by VortixDev** [comment]
Thanks for the PR, though if someone wants to use the setup of the existing third person plugin whilst implementing their own system, they can override the relevant functions - a "custom third person" mechanic is not needed for this.

**Comment by karl-police** [comment]
@VortixDev The mechanic does not add any disadvantages to the current one

**Comment by karl-police** [comment]
@VortixDev also it doesn't need to be overriden anymore it can but it doesn't have to

**Comment by sanny-io** [comment]
The disadvantage to this is that it's unnecessary. It's another way to do something that is already easily accomplished.

**Comment by karl-police** [comment]
> The disadvantage to this is that it's unnecessary. It's another way to do something that is already easily accomplished.

don't you get it that overriding is not really a nice thing?

**Comment by FilmsActionCZ** [comment]
+support

sounds lit

**Comment by sanny-io** [comment]
>don't you get it that overriding is not really a nice thing?

In this case, I don't see anything wrong with an override. What I think would be even better is if there was a hook that was called to enable third person. If the hook doesn't return anything, then the default third person will activate.

**Comment by karl-police** [comment]
> > don't you get it that overriding is not really a nice thing?
> 
> In this case, I don't see anything wrong with an override. What I think would be even better is if there was a hook that was called to enable third person. If the hook doesn't return anything, then the default third person will activate.

you have to know that player NWBool is set per client not for everyone at the same time, each has a different value, there is no problem. This is the best solution I come with.

**Pull request closed without merging**
