### PR TITLE
Fixes example faction

### PR DESCRIPTION
**Pull request by Vizurez**
FACTION.isWhitelisted should be FACTION.whitelisted

### CODE REVIEW

**Comment by Vizurez** [comment]
I still don't know how to use this... anyone know why it says 3 commits when it's only one?

**Comment by xRJx** [comment]
It looks like you have multiple changes from the branch you're trying to merge.

**Comment by Vizurez** [comment]
The first-person legs commit got pushed, so I don't understand how it's marking that as a new commit.

**Comment by xRJx** [comment]
I looked at the commit linked in this discussion and the one that was merged previously. It seems like they're both the same commit, just with different pull request references.

The original: https://github.com/CloudSixteen/Clockwork/pull/416/commits/157759067643edd19551c931aba17095686a3a43

The one linked in this discussion: https://github.com/CloudSixteen/Clockwork/pull/425/commits/157759067643edd19551c931aba17095686a3a43

**Pull request closed without merging**
