### PR TITLE
Fixes issue where blueprints only ever took one item from player

### PR DESCRIPTION
**Pull request by Vizurez**
The 'CheckTakeItems' function would attempt to take the same item from the player x amount of times.

### CODE REVIEW

**Comment by xRJx** [comment]
It'd probably be better to fix the source function:

https://github.com/CloudSixteen/Clockwork/blob/master/Clockwork/garrysmod/gamemodes/clockwork/framework/sv_kernel.lua#L5391

self:TakeItem(self:FindItemByID(itemTable));

**Comment by TacticalToaster** [comment]
I made my own fix to CheckTakeItems that still uses the if statements properly. Not really my best work, as it was a hasty patch to get crafting working as quick as possible for a server, but maybe you all can fix it up.

`function Clockwork.crafting:CheckTakeItems(player, item, amount)
	if (player and item and amount) then
		if (amount > 1) then
			local itemsToTake = {};
			local itemList = Clockwork.inventory:GetItemsByID(player:GetInventory(), item);
			local iterator = 1;
			
			for i, v in pairs(itemList) do
				if iterator <= amount then
					itemsToTake[#itemsToTake + 1] = v;
					iterator = iterator + 1;
				end;
			end;
			
			player:TakeItems(itemsToTake);
		else
			player:TakeItem(player:FindItemByID(item));
		end;
	end;
end;`

**Comment by TacticalToaster** [comment]
Yeah, I did a bunch of testing by printing out the values to the console and saw the issue. I wrote a few fixes but this was the one I ended on. I originally just wanted to do a normal for loop for the amount and do `itemsToTake[#itemsToTake + 1] = itemList[i];` but the indexes of itemList are the itemIDs of the item, so couldn't do it like that. Ended up with that workaround, though I think an else statement and a break would make it a bit more efficient, but not a final solution.

**Comment by xRJx** [comment]
I just finished the code now and actually made it the way you described already haha. I think what I got written should resolve issue, I just changed around some of the variable names to be a bit more descriptive and added the else break ofc. Commit coming soon.

**Comment by TacticalToaster** [comment]
Sweet, glad to help!

**Pull request closed without merging**
