### PR TITLE
Added support for multiple voice commands

### PR DESCRIPTION
**Pull request by karl-police**
Added support for multiple voice commands

this also adds the fix from my other pull request

### CODE REVIEW

**Comment by moschetto** [comment]
Do you want #507 to be closed? In the future, you can amend commits in pull requests, so you don't have to make a second one.

**Comment by karl-police** [comment]
> Do you want #507 to be closed? In the future, you can amend commits in pull requests, so you don't have to make a second one.

Idk, 507 is a change yes. #508 contains these changes

but since apperantly you need more than 1 people to verify it here and I don't know if one pull request gets accepted, if it will merge this one somehow, I just don't know.

**Comment by karl-police** [comment]
So before merging this one, 507 has to be accepted and then 508

**Comment by kurozael** [comment]
I've merged this, but in future please make pull requests for commits to the `develop` branch. In addition, I have manually edited the file to fit more in line with the Clockwork coding style.

**Pull request merged**
